net_file: sumo_rl/nets/2way-single-intersection/single-intersection.net.xml
route_file: sumo_rl/nets/2way-single-intersection/single-intersection-gen.rou.xml
gui: false
num_seconds: 300
min_green: 5
delta_time: 5
no_libsumo: false
log_level: INFO
traffic_scale: 1.0
