net_file: sumo_rl/nets/4x4-Lucas/4x4.net.xml
route_file: sumo_rl/nets/4x4-Lucas/4x4c1c2c1c2.rou.xml
gui: false
num_seconds: 300
min_green: 5
delta_time: 5
no_libsumo: false
log_level: INFO
traffic_scale: 1.0
